log:
    level: info
plugins:
    - args:
        upstreams:
            - addr: https://8.8.8.8/dns-query
      tag: forward_google
      type: forward
    - args:
        entry: forward_google
        listen: 127.0.0.1:53
      tag: udp_server
      type: udp_server
    - args:
        entry: forward_google
        listen: 127.0.0.1:53
      tag: tcp_server
      type: tcp_server
